name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  checks:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: themoretheless/.github/.github/actions/setup-rust@bb3377f2f424201379ab4e47e147f164f4014b38 # v1
        with:
          rust-toolchain: beta

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --locked

      - name: Run tests
        run: cargo test --locked

      - name: Run Clippy
        run: cargo clippy --locked --all-targets -- -D warnings
